### ISSUE TITLE
Jenkins Config as code - Doc needs update - Tool Automatic installation from release.jfrog.io

### ISSUE THREAD

**Issue by psimms-r7** [jfrog/jenkins-jfrog-plugin#53]
### Describe the bug

The code defined for jenkins config as code for the tool and automatic install from jfrogio does not work, more is needed

Under
https://github.com/jfrog/jenkins-jfrog-plugin#jenkins-configuration-as-code

Add JFrog CLI tool using one of the following methods:
[Automatic installation from release.jfrog.io](https://github.com/jfrog/jenkins-jfrog-plugin#automatic-installation-from-releasejfrogio):
```
tool:
  jfrog:
    installations:
      - name: "jfrog-cli"
```

### Current behavior

Error

```
A 'jfrog' tool was not set. Using JFrog CLI from the system path.
```

### Reproduction steps

Needs to be like this to pickup to be installed automatically

```
tool:
  jfrog:
    installations:
    - name: "jfrog-cli"
      properties:
      - installSource:
          installers:
          - "releasesInstaller"
```

### JFrog plugin version

1.2.0

### JFrog CLI version

2.34.6

### Operating system type and version

Jenkins 2.387.1
