### ISSUE TITLE
"Bypass HTTP proxy" resets on deploy of jenkins

### ISSUE THREAD

**Issue by oysandvik94** [jfrog/jenkins-jfrog-plugin#94]
### How can we help?

We package Jenkins in a Docker image and deploy it. 

The option "Bypass HTTP proxy" is unchecked when we deploy. This option:

![image](https://github.com/jfrog/jenkins-jfrog-plugin/assets/25078429/083a5d8a-1113-417c-b0a9-b4983b68fb9b)

We have some config in our configuration.yaml file:

```
unclassified:
  artifactorybuilder:
    useCredentialsPlugin: true
    jfrogInstances:
      - instanceId: artifactory
        artifactoryUrl: **redacted**
        deployerCredentialsConfig:
          credentialsId: 'artifactory_login'
        distributionUrl: **redacted**
        platformUrl: **redacted**
```

I am assuming that the default for this option is false, and when we deploy we overwrite this option with this config. 
I haven't found the name for this option to set it in our config.
